package com.g7.webserviceprojekt;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class AccountsService {

    @Autowired // This means to get the bean called PersonRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AccountRepository AccountRepository;

    public String addNewPerson(String name, String email, String password) {
        Accounts n = new Accounts();
        n.setName(name);
        n.setEmail(email);
        n.setPassword(password);
        AccountRepository.save(n);
        return "Saved";
    }

    public Iterable<Accounts> getAllPersons() {
        return AccountRepository.findAll();
    }

    public Accounts findAccountById(int id) {
        Accounts acc = AccountRepository.findById(id).get();

        return acc;
    }

    public Accounts updateAccountByName(int id, String name) {
        Accounts acc = findAccountById(id);

        acc.setName(name);

        AccountRepository.save(acc);

        acc = findAccountById(id);

        return acc;
    }

}
